function to find the next empty cell
Hack-Weekly/tangerine-moose-sudoku pull request #11
Opened 2023-08-15 06:37 UTC by kruti-w

Part of the solver algorithm

2023-08-15 07:04 UTC, raswonders commented on src/app/components/board.jsx
> +  for (let i = 0; i < index + 1; i++){
This seems to have off by 1 error.

2023-08-15 07:05 UTC, raswonders requested changes
I'm not exactly sure how this function falls into the algo you're implementing I need to see more context I guess.

2023-08-15 08:07 UTC, kruti-w commented on src/app/components/board.jsx
> +  for (let i = 0; i < index + 1; i++){
Fixed it.

2023-08-15 10:20 UTC, kruti-w commented
https://github.com/kruti-w/tangerine-moose-sudoku/tree/solver-algorithm - Solver implementation begun here. I haven't made a PR yet but please feel free to jump in on it! I'll be back online in about 5 hours and can collab then

2023-08-16 00:59 UTC, raswonders commented
I think this is already outdated PR as solve algo is implemented. let me know if we can close it.

2023-08-22 05:10 UTC, closed without merging